### ISSUE TITLE
Is the planet already playable?

### ISSUE THREAD

**Issue by LordDennis18** [lordReddx/GreenTech#2]
Because earlier i saw the planet in this mod showing in the campaign on my other phone. But it doesn't shows up in my other phone. Is it a bug?

**Comment by lordReddx** [comment]
This may or may not be a bug. I advise you to reinstall the mod and see what happens.

**Comment by LordDennis18** [comment]
I've already done that like three times but nothing happens

**Comment by lordReddx** [comment]
Can I see the last_log? (Directly after launching with the mod)

**Comment by LordDennis18** [comment]
how can i show the last_log?

**Comment by LordDennis18** [comment]
I've done a test, i think one of the mods i![Screenshot_2021-04-07-16-31-09-37_13f989b68d7412e5a177fb13b36ac66f.jpg](https://user-images.githubusercontent.com/78860136/113836410-7278d000-97bf-11eb-8d96-8075834210e8.jpg) installed made it unavailable on the campaign for some reason.

**Comment by LordDennis18** [comment]
And here is the planet showing up after i remove all of the mods![Screenshot_2021-04-07-16-32-07-82_13f989b68d7412e5a177fb13b36ac66f.jpg](https://user-images.githubusercontent.com/78860136/113836563-90decb80-97bf-11eb-905f-c0fe0c8fb860.jpg)

**Comment by LordDennis18** [comment]
And here is the log where all the mods i've installed including your mod.![Screenshot_2021-04-07-16-38-24-60_a27b88515698e5a58d06d430da63049d.jpg](https://user-images.githubusercontent.com/78860136/113836970-f59a2600-97bf-11eb-8fd5-d89e2ffca82a.jpg)![Screenshot_2021-04-07-16-38-29-96_a27b88515698e5a58d06d430da63049d.jpg](https://user-images.githubusercontent.com/78860136/113836971-f632bc80-97bf-11eb-8d9c-feaa980b8f29.jpg)

**Comment by lordReddx** [comment]
As far as I understand, everything is OK?

**Comment by LordDennis18** [comment]
It's all working now, the main problem is the octo fictional mod that made it disappear. Mino is appearing in my campaign now.

**Comment by lordReddx** [comment]
Well, I'm glad it works. And as for the fictional octo mod, there are planets added in a different way, maybe because of this it turns out so.
